[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
application = { path = "../../../../core/crates/application", optional = true }
infrastructure = { path = "../../../../core/crates/infrastructure", optional = true }

dioxus = { workspace = true, features = ["fullstack"] }

[features]
server = ["dioxus/server", "dep:application", "dep:infrastructure"]
