services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file: ../.env
    networks:
      - local
    volumes:
      - ../..:/workspaces:cached

  db:
    image: postgres:18-trixie
    env_file: ../.env
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:

networks:
  local:
