services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file: ../.env.dev
    networks:
      - local
    volumes:
      - ../..:/workspaces:cached
      - sqlite-data:/sqlite

  postgres:
    image: postgres:18-trixie
    env_file: ../.env.dev
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped

  postgres-test:
    image: postgres:18-trixie
    env_file: ../.env.test
    ports:
      - "5433:5432"
    networks:
      - local
    volumes:
      - postgres-test-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres-data:
  postgres-test-data:
  sqlite-data:

networks:
  local:
