database:
  uri:
    host: ${DB_HOST}
    port: ${DB_PORT}

  databases:
    admin:
      name: loom_admin
    tenant:
      name_prefix: loom_tenant

  users:
    admin:
      credentials:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    tenant:
      credentials:
        username_prefix: tenant

  pool:
    max_size: 20
    min_size: 5
    timeout_seconds: 30
