database:
  uri:
    host: ${DB_HOST}
    port: ${DB_PORT}

  databases:
    admin:
      name: gyst_admin
    tenant:
      name_prefix: gyst_tenant_

  users:
    admin:
      credentials:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    tenant:
      credentials:
        username_prefix: tenant_

  pool:
    max_size: 20
    min_size: 5
    timeout_seconds: 30
