[package]
name = "infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
admin-migrations = { path = "../migrations/admin" }
shared-migrations = { path = "../migrations/shared" }
tenant-migrations = { path = "../migrations/tenant" }

async-trait = { workspace = true }
dotenvy = { workspace = true }
embassy-futures = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde-vars = "0.2.0"
serde_yaml = "0.9.33"
thiserror = { workspace = true }
url = { workspace = true }

[lints]
workspace = true
