[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { workspace = true }
dioxus = { workspace = true }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components/tree/main/primitives/src", branch = "main" }

[features]
server = ["api/server"]
